import { createElement } from 'lwc';
import Lwc_events_pubsub_publisher from 'c/lwc_events_pubsub_publisher';

describe('c-lwc-events-pubsub-publisher', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Arrange
        const element = createElement('c-lwc-events-pubsub-publisher', {
            is: Lwc_events_pubsub_publisher
        });

        // Act
        document.body.appendChild(element);

        // Assert
        // const div = element.shadowRoot.querySelector('div');
        expect(1).toBe(1);
    });
});